# Database connection
[postgres]
url = "postgresql://neondb_owner:npg_EJYSd2IA0lbp@ep-cold-scene-a6mv9l89-pooler.us-west-2.aws.neon.tech/neondb?sslmode=require"
# old_url = "postgresql://postgres:postgres@localhost:5432/alumni_db"

# NASA API key if needed
# NASA_API_KEY = "hjp6PQBMN7kiHJf28k6EuTLIowh0AOcxPtxLkk1c" 
[nasa] 
api_key = "hjp6PQBMN7kiHJf28k6EuTLIowh0AOcxPtxLkk1c" 
