# Database connection
[postgres]
url = "postgresql://neondb_owner:npg_EJYSd2IA0lbp@ep-cold-scene-a6mv9l89-pooler.us-west-2.aws.neon.tech/neondb?sslmode=require"

# NASA API key
[nasa] 
api_key = "hjp6PQBMN7kiHJf28k6EuTLIowh0AOcxPtxLkk1c" 
